DailyInEx/Controllers/BusinessController.cs
using DailyInEx.Models;
using DataLibrary.BusinessLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DailyInEx.Controllers
{
    public class BusinessController : Controller
    {
        // GET: Business
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Authorize");
        }

        public ActionResult IncomeEntry()
        {
            
            ViewBag.Banks = IncomeExpensesProcessor.LoadBanks();
            return View();
        }

        [HttpPost]
        public ActionResult IncomeEntry(IncomeModel income)
        {
            bool isSaved = IncomeExpensesProcessor.SaveIncome(income.Amount, income.Cash, income.Cheque, income.ChequeNo, income.BankId, income.Particular, income.Date);
            if (isSaved)
            {
                ViewBag.Massage = "Income Saved Successfully";
            }
            else
            {
                ViewBag.Massage = "Sorry Income couldn't save";
            }
            ViewBag.Banks = IncomeExpensesProcessor.LoadBanks();
            return View();
        }



        public ActionResult ExpenseEntry()
        {
            ViewBag.Banks = IncomeExpensesProcessor.LoadBanks();
            return View();
        }

        [HttpPost]
        public ActionResult ExpenseEntry(ExpenseModel expense)
        {
            bool isSaved = IncomeExpensesProcessor.SaveExpense(expense.Amount, expense.Cash, expense.Cheque, expense.ChequeNo, expense.BankId, expense.Particular, expense.Date);
            if (isSaved)
            {
                ViewBag.Massage = "Expense Saved Successfully";
            }
            else
            {
                ViewBag.Massage = "Sorry Expense couldn't save";
            }
            ViewBag.Banks = IncomeExpensesProcessor.LoadBanks();
            return View();
        }

    }
}

DailyInEx/Controllers/ReportController.cs
using DataLibrary.BusinessLogic;
using DataLibrary.BusinessModel;
using DataLibrary.BusinessModel.ViewModel;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DailyInEx.Controllers
{
    public class ReportController : Controller
    {

        // GET: Report
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult IncomeMonthly(int? year, int? month)
        {
            if (year != null & month != null)
            {
                List<IncomeMonthlyView> incomes = ReportProcessor.GetMonthlyIncome((int)year, (int)month);

                if (incomes.Count > 0)
                {
                    ViewBag.Message = incomes.Count + " data found";
                    ViewBag.IncomeList = incomes;
                }
                else
                {
                    ViewBag.Message = "No Data found";
                }
            }
            ViewBag.ListOfYear = ReportProcessor.ListOfYear();
            return View();
        }

        public ActionResult ExpenseMonthly(int? year, int? month)
        {
            if (year != null & month != null)
            {
                List<ExpenseMonthlyView> expenses = ReportProcessor.GetMonthlyExpense((int)year, (int)month);

                if (expenses.Count > 0)
                {
                    ViewBag.Message = expenses.Count + " data found";
                    ViewBag.ExpenseList = expenses;
                }
                else
                {
                    ViewBag.Message = "No Data found";
                }
            }
            ViewBag.ListOfYear = ReportProcessor.ListOfYear();
            return View();
        }

        public ActionResult YearlyReport(int? year)
        {
            if (year != null)
            {
                List<YearlyInExView> yearlyReportList = ReportProcessor.GetYearlyInExRepot((int)year);
                ViewBag.Report = yearlyReportList;
            }
            else
            {
                ViewBag.Message = "No data found";
            }
            ViewBag.Year = year;
            ViewBag.ListOfYear = ReportProcessor.ListOfYear();

            return View();
        }
        public ActionResult YearlyPdf(int? year)
        {
            if (year != null)
            {
                
                return new ActionAsPdf("YearlyReportView") { FileName = "YearlyView.pdf" };
            }

            return RedirectToAction("YearlyReport");
        }

        public ActionResult YearlyReportView()
        {
            int? year = 2019;
            List<YearlyInExView> yearlyReportList = ReportProcessor.GetYearlyInExRepot((int)year);
            ViewBag.Report = yearlyReportList;
            ViewBag.Year = year;


            return View();
        }
    }
}

DailyInEx/Views/Shared/_Layout - Authorized.cshtml
@{
    if (Session["user"] == null)
    {
        Response.Redirect("~/Authorize/Login");
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DailyInEx", "Index", "Authorize", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Incomes
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Income Entry", "IncomeEntry", "Business")</li>
                            <li>@Html.ActionLink("Pending Incomes", "ApproveIncome", "ApproveInEX")</li>
                            <li>@Html.ActionLink("Monthly Income Report", "IncomeMonthly", "Report")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Expenses
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Expenses Entry", "ExpenseEntry", "Business")</li>
                            <li>@Html.ActionLink("Pending Expenses", "ApproveExpense", "ApproveInEX")</li>
                            <li>@Html.ActionLink("Monthly Expense Report", "ExpenseMonthly", "Report")</li>

                        </ul>
                    </li>
                    <li>@Html.ActionLink("View Yearly Report", "YearlyReport", "Report")</li>

                </ul>
                <div class="nav navbar-nav navbar-right">
                    <a href="" class="navbar-brand">Hello @Session["user"]</a>
                    <a href="~/Authorize/Logout" class="navbar-brand"><strong>Logout</strong></a>
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DailyInEx/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>